# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-05 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestartup', '0002_place_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.FileField(default=2, upload_to='places'),
            preserve_default=False,
        ),
    ]
