# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-07 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestartup', '0003_place_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.FileField(blank=True, upload_to='places'),
        ),
    ]
