# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-10 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestartup', '0004_auto_20180207_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='has_kitchen',
            field=models.BooleanField(default=False),
        ),
    ]
